apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: sandor@lukacsi.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: { name: le-account-key }
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

# future work: move to http challenge