apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public-gw-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          cloud.google.com/l4-rbs: "enabled"
          networking.gke.io/load-balancer-ip-addresses: envoy-ip

