apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: livekit-media-plane
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: livekit-sig
          namespace: livekit-a
        - name: livekit-sig
          namespace: livekit-b
# uj udproute minden livekitre
